# Generated by Django 4.1.3 on 2022-11-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprotfolio', '0004_alter_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, height_field=250, null=True, upload_to='', width_field=250),
        ),
    ]
